### ISSUE TITLE
Add support for custom hostname

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/terraform-aws-flowfuse#8]
### Description

See FlowFuse/flowfuse#324

### Requested By

- prep for furture

**Comment by joepavitt** [comment]
Can you add a sizing for this please @ppawlowski?

**Comment by ppawlowski** [comment]
As far as I remember the only infrastructure-related stuff which needs to be created is a load balancer, which is controlled by the dedicated ingress controller. I do not recall creating any other infrastructure-related resources which will require adjustments to our terraform modules.
@hardillb am I missing sommeting?

**Comment by hardillb** [comment]
The only other change I can think of was adding a DNS entry for the new load balancer to make the customer target easier (and if the loadblancer changed)

**Comment by joepavitt** [comment]
Just checked in with Piotr, should be closed this week
